argoNamespace: argocd
argoProject: default

labels:
  team: eyjo
  app: eyjo-app
  environment: dev
  env: "${env}"

spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: "${repoUrl}"
    targetRevision: "${targetRevision}"
  
  blueprint: service
  clusterName: "${clusterName}"
  env: "${env}"
  
  ingress:
    type: "nginx"
    className: "nginx-tls"
    host: "${host}"
    route53_weight: "${route53_weight}"
  
  karpenterInstanceProfile: "${karpenterInstanceProfile}"
    
service:
  name: eyjo-service
  port: 80
  targetPort: 8080

deployment:
  name: eyjo-deployment
  replicas: 2
  image: nginx:latest
  containerPort: 8080
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "128Mi"
      cpu: "200m"

ingress:
  name: eyjo-ingress
  path: /eyjo
  pathType: Prefix