apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: team-eyjo
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: eyjo-app
  template:
    metadata:
      labels:
        app: eyjo-app
    spec:
      containers:
      - name: eyjo-container
        image: {{ .Values.deployment.image }}
        imagePullPolicy: Always
        env:
        - name: CLUSTER_NAME
          value: {{ .Values.spec.clusterName }}
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        resources:
          {{- toYaml .Values.deployment.resources | nindent 10 }}
      {{ if .Values.spec.karpenterInstanceProfile }}
      nodeSelector:
        team: eyjo
        type: karpenter
      tolerations:
        - key: 'eyjo'
          operator: 'Exists'
          effect: 'NoSchedule'
      {{ end }}