# teams/team-eyjo/dev/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.applicationName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.applicationName }}
    env: {{ .Values.spec.env }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.applicationName }}
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}
        env: {{ .Values.spec.env }}
    spec:
      containers:
      - name: {{ .Values.applicationName }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
          name: http
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        env:
        {{- range .Values.env }}
        - name: {{ .name }}
          value: "{{ .value }}"
        {{- end }}
        {{- if .Values.configMap.enabled }}
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        {{- end }}
      {{- if .Values.configMap.enabled }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Values.applicationName }}-config
      {{- end }}
