apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: team-eyjo
  labels:
    app: nginx
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx