apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: team-eyjo
  labels:
    app: nginx
    {{- toYaml .Values.labels | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
{{ if .Values.spec.ingress.host }}
    external-dns.alpha.kubernetes.io/set-identifier: {{ .Values.spec.clusterName }}
    external-dns.alpha.kubernetes.io/aws-weight: '{{ .Values.spec.ingress.route53_weight }}'
    external-dns.alpha.kubernetes.io/ttl: "10"
{{ end }}
spec:
  ingressClassName: {{ .Values.spec.ingress.className }}
  rules:
{{ if .Values.spec.ingress.host }}
  - host: nginx.{{ .Values.spec.ingress.host }}
{{ else }}
  - host:
{{ end }}
    http:
      paths:
      - path: /nginx
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80