apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: team-eyjo
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  selector:
    app: eyjo-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: ClusterIP